// Danh sách sở thích tiếng Việt kèm icon
// Định dạng: { name: 'English', vi: 'Tiếng Việt', icon: '...' }
export const HOBBIES_VI = [
  { name: "Art", vi: "Nghệ thuật", icon: "🎨" },
  { name: "Painting", vi: "Vẽ tranh", icon: "🖌️" },
  { name: "Drawing", vi: "Vẽ", icon: "✏️" },
  { name: "Sculpture", vi: "Điêu khắc", icon: "🗿" },
  { name: "Digital Art", vi: "Nghệ thuật số", icon: "💻" },
  { name: "Illustration", vi: "Minh họa", icon: "🖍️" },
  { name: "Graphic Design", vi: "Thiết kế đồ họa", icon: "🖼️" },
  { name: "Animation", vi: "Hoạt hình", icon: "🎞️" },
  { name: "Calligraphy", vi: "Thư pháp", icon: "🖋️" },
  { name: "Photography", vi: "Nhiếp ảnh", icon: "📷" },
  { name: "Filmmaking", vi: "Làm phim", icon: "🎬" },
  { name: "Pottery", vi: "Gốm sứ", icon: "🏺" },
  { name: "Jewelry Making", vi: "Làm trang sức", icon: "💍" },
  { name: "Knitting", vi: "Đan len", icon: "🧶" },
  { name: "Crocheting", vi: "Móc len", icon: "🧵" },
  { name: "Quilting", vi: "Chần bông", icon: "🪡" },
  { name: "Sewing", vi: "May vá", icon: "🧵" },
  { name: "Embroidery", vi: "Thêu", icon: "🪡" },
  { name: "Candle Making", vi: "Làm nến", icon: "🕯️" },
  { name: "DIY Crafts", vi: "Thủ công DIY", icon: "🛠️" },
  { name: "Music", vi: "Âm nhạc", icon: "🎵" },
  { name: "Playing Guitar", vi: "Chơi guitar", icon: "🎸" },
  { name: "Playing Piano", vi: "Chơi piano", icon: "🎹" },
  { name: "Playing Drums", vi: "Chơi trống", icon: "🥁" },
  { name: "Playing Violin", vi: "Chơi violin", icon: "🎻" },
  { name: "Singing", vi: "Ca hát", icon: "🎤" },
  { name: "Songwriting", vi: "Sáng tác nhạc", icon: "📝" },
  { name: "Music Production", vi: "Sản xuất âm nhạc", icon: "🎚️" },
  { name: "DJing", vi: "DJ", icon: "🎧" },
  { name: "Classical Music", vi: "Nhạc cổ điển", icon: "🎼" },
  { name: "Jazz", vi: "Nhạc jazz", icon: "🎷" },
  { name: "Rock Music", vi: "Nhạc rock", icon: "🎸" },
  { name: "Pop Music", vi: "Nhạc pop", icon: "🎤" },
  { name: "Hip Hop", vi: "Hip hop", icon: "🎧" },
  { name: "Electronic Music", vi: "Nhạc điện tử", icon: "🎛️" },
  { name: "Country Music", vi: "Nhạc đồng quê", icon: "🪕" },
  { name: "R&B", vi: "R&B", icon: "🎶" },
  { name: "Opera", vi: "Nhạc opera", icon: "🎭" },
  { name: "Choir", vi: "Hợp xướng", icon: "👨‍🎤" },
  { name: "Musical Theater", vi: "Nhạc kịch", icon: "🎟️" },
  { name: "Books", vi: "Sách", icon: "📚" },
  { name: "Reading", vi: "Đọc sách", icon: "📖" },
  { name: "Creative Writing", vi: "Viết sáng tạo", icon: "✍️" },
  { name: "Poetry", vi: "Thơ", icon: "📝" },
  { name: "Fiction Writing", vi: "Viết truyện", icon: "📖" },
  { name: "Non-fiction Writing", vi: "Viết phi hư cấu", icon: "📄" },
  { name: "Screenwriting", vi: "Viết kịch bản", icon: "📝" },
  { name: "Playwriting", vi: "Viết kịch", icon: "🎭" },
  { name: "Blogging", vi: "Viết blog", icon: "📰" },
  { name: "Journalism", vi: "Báo chí", icon: "🗞️" },
  { name: "Book Clubs", vi: "Câu lạc bộ sách", icon: "📚" },
  { name: "Literary Analysis", vi: "Phân tích văn học", icon: "🔍" },
  { name: "Storytelling", vi: "Kể chuyện", icon: "📖" },
  // ... (tiếp tục cho các sở thích còn lại)
];
